name: Basic CI Pipeline
on: 
  push:
    branches: [ main ]
jobs:
  test_app:
    name: Run All Tests & Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Server - Install & Test
        run: |
          cd server
          npm ci
          npm run lint
          npm test

      - name: Client - Install & Test
        run: |
          cd client
          npm ci
          npm run lint
          npx vitest run
